package compiler.AST;

public class NotEquals extends Expression {
    public Expression left;
    public Expression right;

    public NotEquals(Expression left, Expression right) {
        this.left = left;
        this.right = right;
    }

    @Override
    public void printDebug(int indent) {
        printIndentation(indent); System.out.println("[NOT EQUALS]");
        printIndentation(indent); System.out.println(" -Left:");
        left.printDebug(indent + 1);
        printIndentation(indent); System.out.println(" -Right:");
        right.printDebug(indent + 1);
    }

    @Override
    public void printASM() {
        int uniqueID = getUniqueID();
        comment("Start NotEquals");

        // PROJECT 8 TODO
        // (Step 4)

        // After reading through Equals, implement NotEquals.
        // You may copy and paste some or all of Equals and modify as you see fit.

        // Estimated lines of code in solution: ~21

        // evaluate `left`
        left.printASM();
        // grab the result of evaluating `left` from R0
        instr("@R0");
        instr("D=M");
        // push onto the stack (see ASTNode.java for the code generated by push())
        push();
        // evaluate `right`
        right.printASM();
        // grab the result of evaluating `right` from R0
        instr("@R0");
        instr("D=M");
        // grab the previously stored value by "dereferencing" R1 (the stack pointer)
        instr("@R1");
        instr("A=M");
        
        // perform the equality check!
        instr("D=M-D", "subtract to check equality");
        instr("@NOTEQUALBRANCH" + uniqueID);
        instr("D;JNE");
        instr("D=0", "probably not necessary but kept just in case");
        instr("@NOTEQUALEND" + uniqueID);
        instr("0;JMP");
        label("NOTEQUALBRANCH" + uniqueID);
        instr("D=1");
        label("NOTEQUALEND" + uniqueID);
        // store in R0
        instr("@R0");
        instr("M=D");
        // pop from the stack (see ASTNode.java for the code generated by pop())
        pop();


        comment("End NotEquals");
    }
}